version: '2'

volumes:
  orderer.kyc.com:
  peer0.Bank.kyc.com:
  peer1.Bank.kyc.com:
  peer0.Client.kyc.com:
  peer1.Client.kyc.com:
  peer0.Validator.kyc.com:
  peer1.Validator.kyc.com:

networks:
  kycnet:

services:

  bankCa.kyc.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Bank.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e56a551d66c1a6a4f347ffc7a2b81184beccb30bbd78c567faaaaf7b4f87a8d8_sk
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Bank.kyc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e56a551d66c1a6a4f347ffc7a2b81184beccb30bbd78c567faaaaf7b4f87a8d8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Bank.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: bankca.kyc.com
    networks:
      - kycnet

  clientCa.kyc.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Client.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c402e4f7ac93a8be45ce5486267d519b8a0b6910d9ade67a8fef723a8fea20b9_sk
    ports:
      - "6064:6064"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Client.kyc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c402e4f7ac93a8be45ce5486267d519b8a0b6910d9ade67a8fef723a8fea20b9_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Client.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: clientca.kyc.com
    networks:
      - kycnet

  validatorCa.kyc.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.kyc.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.Validator.kyc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b6aa8c9dac7673e9b2e4b7e68d59c23e4e8b12e790b5da13ecec06c44a7964ab_sk
    ports:
      - "6074:6074"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Validator.kyc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b6aa8c9dac7673e9b2e4b7e68d59c23e4e8b12e790b5da13ecec06c44a7964ab_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/Validator.kyc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: validatorca.kyc.com
    networks:
      - kycnet

  orderer.kyc.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.kyc.com
    container_name: orderer.kyc.com
    networks:
      - kycnet

  peer0.Bank.kyc.com:
    container_name: peer0.Bank.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Bank.kyc.com
    networks:
      - kycnet

  peer1.Bank.kyc.com:
    container_name: peer1.Bank.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Bank.kyc.com
    networks:
      - kycnet

  peer0.Client.kyc.com:
    container_name: peer0.Client.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Client.kyc.com
    networks:
      - kycnet

  peer1.Client.kyc.com:
    container_name: peer1.Client.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Client.kyc.com
    networks:
      - kycnet

  peer0.Validator.kyc.com:
    container_name: peer0.Validator.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.Validator.kyc.com
    networks:
      - kycnet

  peer1.Validator.kyc.com:
    container_name: peer1.Validator.kyc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.Validator.kyc.com
    networks:
      - kycnet

  bankcli:
    container_name: bankcli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=bankcli
      - CORE_PEER_ADDRESS=peer0.Bank.kyc.com:7051
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Bank.kyc.com/peers/peer0.Bank.kyc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Bank.kyc.com/peers/peer0.Bank.kyc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Bank.kyc.com/peers/peer0.Bank.kyc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Bank.kyc.com/users/Admin@Bank.kyc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.kyc.com
      - peer0.Bank.kyc.com
      - peer1.Bank.kyc.com
      - peer0.Client.kyc.com
      - peer1.Client.kyc.com
      - peer0.Validator.kyc.com
      - peer1.Validator.kyc.com
    networks:
      - kycnet

  clientcli:
    container_name: clientcli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=clientcli
      - CORE_PEER_ADDRESS=peer0.Client.kyc.com:9051
      - CORE_PEER_LOCALMSPID=ClientMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Client.kyc.com/peers/peer0.Client.kyc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Client.kyc.com/peers/peer0.Client.kyc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Client.kyc.com/peers/peer0.Client.kyc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Client.kyc.com/users/Admin@Client.kyc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.kyc.com
      - peer0.Bank.kyc.com
      - peer1.Bank.kyc.com
      - peer0.Client.kyc.com
      - peer1.Client.kyc.com
      - peer0.Validator.kyc.com
      - peer1.Validator.kyc.com
    networks:
      - kycnet

  validatorcli:
    container_name: validatorcli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=validatorcli
      - CORE_PEER_ADDRESS=peer0.Validator.kyc.com:11051
      - CORE_PEER_LOCALMSPID=ValidatorMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Validator.kyc.com/peers/peer0.Validator.kyc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Validator.kyc.com/peers/peer0.Validator.kyc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Validator.kyc.com/peers/peer0.Validator.kyc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Validator.kyc.com/users/Admin@Validator.kyc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.kyc.com
      - peer0.Bank.kyc.com
      - peer1.Bank.kyc.com
      - peer0.Client.kyc.com
      - peer1.Client.kyc.com
      - peer0.Validator.kyc.com
      - peer1.Validator.kyc.com
    networks:
      - kycnet